### ISSUE TITLE
Serilog

### ISSUE THREAD

**Issue by tylermichael** [logtail/logtail-dotnet#3]
Is there a way to use logtail as a serilog sink?

**Comment by Herostwist** [comment]
I was considering using Logtail but we are heavily invested in Serilog and I was hoping by now there would have been an answer to this issue.

**Comment by gyfis** [comment]
Hi @tylermichael and @Herostwist! I wanted to let you know that we do have Serilog support in our development pipeline, though it's not ready yet. We'll keep you updated here once we make progress with it!

**Comment by saiganov** [comment]
Any progress with Serilog?

**Comment by WaldoAndFriends** [comment]
Glad to see it's on the roadmap, just dropping in to +1 on the interest.

**Comment by m7jakob** [comment]
Is there any progress on this?

**Comment by PetrHeinz** [comment]
Hello everyone!

You can pass logs from Serilog to NLog via `Serilog.Sinks.NLog`. First add packages to your project:

```bash
dotnet add package Logtail
dotnet add package Serilog.Sinks.NLog
```

Add `nlog.config` configuration file to the root of your project (just replace `SOURCE_TOKEN` with your actual source token):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="internal.txt">
  <extensions>
    <add assembly="Logtail" />
  </extensions>

  <targets>
    <!-- Dont forget to change SOURCE_TOKEN to your actual source token-->
    <target xsi:type="Logtail" name="logtail" sourceToken="SOURCE_TOKEN" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="logtail" />
  </rules>
</nlog>
```

Add following configuration to your `.csproj` file:

```xml
  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

And then add the sink `.WriteTo.NLog()` to your Serilog configuration:

```csharp
Log.Logger = new LoggerConfiguration()
  .WriteTo.Console()
  .WriteTo.NLog()
  .MinimumLevel.Info()
  .CreateLogger();
```

Now your project should be ready to sent the logs to Better Stack via Serilog. I've tested it on an example project with both .NET `v6.0.412` and `v8.0.100-preview.6.23330.14`. Works like a charm in both 🙂

Hope this helps!

**Comment by PetrHeinz** [comment]
Hey there, I'm closing this issue as resolved since there isn't any feedback I can work on further. Don't hesitate to reopen the issue if you find the way of using Serilog I'e described as not fulfilling your needs 🙂
