### ISSUE TITLE
Fails to load with NLog 5.0.0

### ISSUE THREAD

**Issue by faina09** [logtail/logtail-dotnet#6]
Upgrading package NLog.Extensions.Logging from 1.7.4 to the next available 5.0.0 I get the message:
> Could not load type 'NLog.Internal.IUsesStackTrace' from assembly 'NLog, Version=5.0.0.0 (...)

To fix I update the ref in logtail-dotnet :
`<PackageReference Include="NLog" Version="5.0.0" />`
and pack to Logtail.0.2.2.nupkg

**Comment by snakefoot** [comment]
Created #7 that makes it work with both NLog4 + NLog5
